"""Initial migration

Revision ID: bf43ebab841d
Revises: 
Create Date: 2025-02-22 21:43:45.742985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf43ebab841d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('use_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_for_text_generation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_models_id'), 'use_models', ['id'], unique=False)
    op.create_index(op.f('ix_use_models_user_id'), 'use_models', ['user_id'], unique=False)
    op.create_table('conversation_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=5000), nullable=True),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_posts_conversation_id'), 'conversation_posts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_posts_id'), 'conversation_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_posts_id'), table_name='conversation_posts')
    op.drop_index(op.f('ix_conversation_posts_conversation_id'), table_name='conversation_posts')
    op.drop_table('conversation_posts')
    op.drop_index(op.f('ix_use_models_user_id'), table_name='use_models')
    op.drop_index(op.f('ix_use_models_id'), table_name='use_models')
    op.drop_table('use_models')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
